# Use Alpine Linux as the base image
FROM alpine

# Set the default command
CMD ["echo", "hello"]


#Build the Image
#cd cmd-test
#docker build -t cmdtest:latest .
---
# Run the Container
# docker run --rm cmdtest:latest

# Output
# hello
---
# Override the CMD
# docker run --rm cmdtest:latest echo world

# Output
# world
