name: Greeting Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom greeting action
        id: greet
        uses: ./.github/actions/setup-and-greet
        with:
          name: Nandan
          language: en

      - name: Verify output
        run: |
          echo "Greeting executed: ${{ steps.greet.outputs.greeted }}"
