# Use Alpine Linux as the base image
FROM alpine

# Set the default executable
ENTRYPOINT ["echo"]

---

# Build the Image
# cd entrypoint-test
# docker build -t entrytest:latest .

# Run the Container
# docker run --rm entrytest:latest hello

# Output
# hello
---
# Pass Multiple Arguments
# docker run --rm entrytest:latest world foo

# Output
# world foo
