# Use Ubuntu as the base image
FROM ubuntu:latest

# Update package lists and install curl
RUN apt-get update && apt-get install -y curl

# Set the default command
CMD echo "Hello from my custom image!"

---

# Build the Image
# cd my-first-image
# docker build -t my-ubuntu:v1 .
---
# Run the Container
# docker run --rm my-ubuntu:v1
---
# Expected Output
# Hello from my custom image!
