# Stage 1: Build
FROM golang:1.24-alpine AS builder

WORKDIR /build

# Copy Go source code
COPY main.go .

# Build a statically linked Go binary
RUN CGO_ENABLED=0 GOOS=linux go build -o hello main.go


# Stage 2: Runtime
FROM alpine:3.22

WORKDIR /app

# Copy only the compiled binary from builder
COPY --from=builder /build/hello .

# Run as non-root user
USER nobody

CMD ["./hello"]
